#!/bin/bash

#

# chkconfig: 35 90 12

# description: testserver server

#

 

# Get function from functions library

. /etc/init.d/functions

 

# Start the service testserver


start() {
    

        echo -n $"Starting eos server: "

        /opt/eos/bin/eos.sh
        
    
        #daemon /usr/share/testserver/testserver &

        ### Create the lock file ###

        touch /var/lock/subsys/eos

        success $"eos server startup"

        echo

}

 

# Restart the service testserver

stop() {

        echo -n $"Stopping testserver server: "
        
        eosps="`ps ax | grep java | grep /opt/eos | grep -o "[^ ]\+\( \+[^ ]\+\)*" | cut -d ' ' -f1`";
        echo "eos进程号：$eosps"
        if [ "$eosps"!="" ]
        then
            kill -9 $eosps ;
            echo "成功结束";
        fi;
        if [ "$eosps" == "" ] 
        then
            echo "没有启动eos";
        fi;
        
        ### Now, delete the lock file ###

        rm -f /var/lock/subsys/eos

        echo

}

rc=

### main logic ###

case "$1" in

  start)

        start

rc=${?}

        ;;

  stop)

        stop

rc=${?}

        ;;

  status)

        status testserver

rc=${?}

        ;;

  restart)

        stop

        sleep 1

        start

        ;;

  *)

        echo $"Usage: $0 {start|stop|restart|status}"

        exit 1

esac

 

exit ${rc}

